// Reproducible checks for the archive and live identity / week logic.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const els=new Map();function el(id){if(!els.has(id)){const classList={toggle(){},add(){},remove(){}};els.set(id,{innerHTML:'',textContent:'',value:'',dataset:{},style:{},hidden:false,classList,parentElement:{classList},setAttribute(){},getAttribute(){return'false'},addEventListener(){},scrollIntoView(){},querySelectorAll(){return[]}});}return els.get(id);}
const nav=['home','history','teams','season2026','transactions','matchups','players','draft'].map(page=>({...el(page),dataset:{page}}));
const context={window:{scrollTo(){}},document:{getElementById:el,querySelectorAll(sel){return sel==='.nav-link'?nav:[]},addEventListener(){},body:{style:{}}},history:{replaceState(){}},location:{hash:'#home'},console,URL};
vm.createContext(context);
for(const file of ['public/data/site-data.js','public/data/history-data.js','public/data/award-data.js','public/data/lineup-data.js','public/data/photo-data.js','public/data/keepers-2026.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context);
const users=[{user_id:'a',display_name:'jdunnigan',metadata:{team_name:"Annie's Boobs"}},{user_id:'b',display_name:'Zwack',metadata:{team_name:'Cheese Curds'}}];
const rosters=[{roster_id:1,owner_id:'a',settings:{wins:1,losses:0},players:['9509']},{roster_id:2,owner_id:'b',settings:{wins:0,losses:1},players:['4984']}];
const league={settings:{last_scored_leg:1},roster_positions:['QB','RB']};
const players={'9509':{full_name:'Bijan Robinson',position:'RB',team:'ATL',fantasy_positions:['RB']},'4984':{full_name:'Josh Allen',position:'QB',team:'BUF',fantasy_positions:['QB']}};
const picks=[{player_id:'9509',roster_id:1,metadata:{amount:'75'},is_keeper:false}];
const weeks={1:[{roster_id:1,matchup_id:1,points:30,players:['9509'],starters:['9509'],players_points:{'9509':30}},{roster_id:2,matchup_id:1,points:20,players:['4984'],starters:['4984'],players_points:{'4984':20}}],2:[{roster_id:1,matchup_id:1,points:0,players:[],starters:[]},{roster_id:2,matchup_id:1,points:0,players:[],starters:[]}]};
const SL={data:{users,rosters,league,picks,state:{week:2},players,weeks,transactions:{},projections:{},rosProjections:{},stats:{}},currentWeek(){return 2},roster(id){return rosters.find(x=>x.roster_id==id)},rosterUser(r){return users.find(x=>x.user_id==r?.owner_id)},managerName(r){return this.rosterUser(r)?.display_name||''},teamName(r){let u=this.rosterUser(r);return u?.metadata?.team_name||u?.display_name||''},player(id){return players[id]||{full_name:`Player ${id}`,position:''}},fullName(id){return this.player(id).full_name},headshot(){return ''},pickPlayerId(p){return String(p.player_id)},pickCost(p){return p.metadata?.amount==null?null:Number(p.metadata.amount)},projectionPoints(){return 0},statPoints(){return 0},ready:Promise.resolve()};
context.window.DIRTY_DS_LIVE=SL;
vm.runInContext(fs.readFileSync(path.join(root,'public/assets/js/app.js'),'utf8'),context);
const run=code=>vm.runInContext(code,context);
assert.equal(run('canonicalManager(SL.roster(1))'),'Jack');
assert.equal(run('canonicalManager(SL.roster(2))'),'Ben');
assert.equal(run('completedWeeks().join(",")'),'1');
assert.equal(run('weekRecord(recordAt(1,1))'),'1–0');
assert.equal(run('weekRecord(recordAt(2,1))'),'0–1');
assert.equal(run("recordsFor('all').find(x=>x.title==='Largest Auction Purchase').value"),'$75');
assert.equal(run("recordsFor('all').find(x=>x.title==='Largest Auction Purchase').team"),'Bijan Robinson');
assert.equal(run("recordsFor('all').find(x=>x.title==='Goat').year"),2018);
run("currentPage='history';renderHistory()");assert.match(el('recordWall').innerHTML,/Bijan Robinson/);assert.match(el('recordWall').innerHTML,/POSITION PRODUCTION/);assert.match(el('app').innerHTML,/data-champion-year="2025"/);
assert.equal(context.window.DIRTY_DS_LINEUPS.championships['2025'].score,217.54);
assert.equal(context.window.DIRTY_DS_LINEUPS.championships['2025'].starters.find(p=>p.name==='Derrick Henry').points,45.6);
run('showChampionship(2025)');assert.match(el('modalContent').innerHTML,/Derrick Henry/);
run("currentPage='teams';drawTeamsPage(true)");assert.equal((el('app').innerHTML.match(/data-manager=/g)||[]).length,13);assert.match(el('app').innerHTML,/HISTORICAL MANAGERS/);assert.match(el('app').innerHTML,/data-manager="Hunter"/);assert.doesNotMatch(el('app').innerHTML,/team-photo has-photo/);
run("showManager('Tyler')");assert.match(el('modalContent').innerHTML,/Top 10 Most Started Players \(Points Scored\)/);assert.match(el('modalContent').innerHTML,/Final place: 1st/);assert.match(el('modalContent').innerHTML,/ PA/);
assert.notEqual(run("recordsFor('all').find(x=>x.title==='COTY').value"),'Unavailable');assert.equal(run("recordsFor('2018').find(x=>x.title==='Cheapskate').value"),'Unavailable');assert.notEqual(run("recordsFor('2024').find(x=>x.title==='Least RB Points · Season').value"),'Unavailable');assert.equal(run("recordDefinitions().some(x=>['Daddy Warbucks','Storage Wars','Turtling'].includes(x[0]))"),false);
for(const year of [2018,2019,2020,2021,2022,2023,2024,2025,2026])for(const title of ['Closest Game','Biggest Blowout','Highest Scoring Week','Lowest Scoring Week'])assert.notEqual(run(`recordsFor('${year}').find(x=>x.title==='${title}').value`),'Unavailable',`${year}: ${title}`);
run("currentPage='season2026';liveWeek=1;drawSeason2026()");assert.doesNotMatch(el('app').innerHTML,/id="livePowerRankings"/);
run("currentPage='power';powerView='jack';drawPowerRankings()");assert.match(el('livePowerContent').innerHTML,/Drake London/);
run("powerView='analyst';drawPowerRankings()");assert.match(el('livePowerContent').innerHTML,/1,000 remaining-season simulations/);
assert.equal(run('liveDraftRows().filter(x=>x.keeper).length'),33);
for(const [position,count] of [['QB',1],['RB',2],['WR',3],['TE',2],['K',1]])for(let i=1;i<=count;i++){const id=`ATL-${position}${i}`;players[id]={player_id:id,full_name:`Test ${position} ${i}`,position,team:'ATL',status:'Active',depth_chart_order:i};}
assert.equal(run("nflLineup('ATL').length"),10);
assert.equal(run("nflLineup('ATL').filter(x=>x.owner==='Free Agent').length"),10);
assert.match(run("formation(nflLineup('ATL'),true,true)"),/z-backs[\s\S]*Test K 1[\s\S]*ATL D\/ST/);
run("currentPage='players';drawPlayersPage(true)");run("playerProfile('Bijan Robinson','9509')");assert.match(el('modalContent').innerHTML,/Career starts/);assert.match(el('modalContent').innerHTML,/\$75/);assert.match(el('modalContent').innerHTML,/Trophy case/);assert.match(el('playerResults').innerHTML,/sleepercdn.com/);
assert.match(el('playerResults').innerHTML,/career points/);assert.doesNotMatch(el('playerResults').innerHTML,/auction \/ keeper entries/);
players.lamar={player_id:'lamar',full_name:'Lamar Jackson',position:'QB',team:'BAL'};picks.push({player_id:'lamar',roster_id:1,metadata:{amount:'41'},is_keeper:false});
run("playerProfile('Lamar Jackson','lamar')");
const lamarHistory=el('modalContent').innerHTML.split('<h3>Draft history</h3>')[1].split('</div></div><div class="dd-modal-block">')[0];
assert.equal((lamarHistory.match(/<strong>2026<\/strong>/g)||[]).length,1);assert.match(lamarHistory,/2026<\/strong><span>James · Keeper/);assert.doesNotMatch(lamarHistory,/2026<\/strong><span>Jack · Draft/);
const trade={transaction_id:'trade-1',status:'complete',type:'trade',leg:1,created:1,roster_ids:[1,2],adds:{'9509':2,'4984':1},draft_picks:[{season:'2027',round:2,owner_id:1,previous_owner_id:2}],waiver_budget:[{receiver:2,sender:1,amount:7}]};
const waiver={transaction_id:'waiver-1',status:'complete',type:'waiver',leg:1,created:2,roster_ids:[1],adds:{'9509':1},drops:{'4984':1},settings:{waiver_bid:12}};
SL.data.transactions={1:[trade,waiver],2:[{transaction_id:'move-2',status:'complete',type:'free_agent',leg:2,created:3,roster_ids:[2],adds:{'4984':2},drops:{}}]};
assert.equal(run('completedTransactions().length'),3);
run("currentPage='transactions';transactionWeek=1;drawTransactionsPage()");assert.match(el('app').innerHTML,/James|Jack/);assert.match(el('app').innerHTML,/2027 round 2 pick/);assert.match(el('app').innerHTML,/\$7 FAAB/);assert.match(el('txMoveResults').innerHTML,/\$12 FAAB/);assert.match(el('txMoveResults').innerHTML,/DROPPED/);
run('transactionWeek=2;drawTransactionMoves(completedTransactions().filter(t=>t.type!==\'trade\'))');assert.match(el('txMoveResults').innerHTML,/Free agent/);
console.log('PASS: archive, season records, keeper precedence, transactions, teams and profiles');
